swagger: '2.0'
schemes:
  - http
host: 'api.funshouts.com:80'
info:
  description: "FunShouts allows you to leave a simple voice mail message (a 'shout') by calling the hotline."
  title: FunShoutsAPI
  version: v1
  x-apiClientRegistration:
    url: 'http://api.funshouts.com/'
  x-logo:
    url: 'https://apis-guru.github.io/api-models/cache/funshouts.com/v1/logo.jpeg'
  x-origin:
    format: swagger
    url: 'http://api.funshouts.com/swagger/docs/v1'
    version: '2.0'
  x-providerName: funshouts.com
externalDocs:
  url: 'http://api.funshouts.com/'
securityDefinitions:
  apiKey:
    description: API Key Authentication
    in: query
    name: apiKey
    type: apiKey
paths:
  /api/shouts:
    get:
      consumes: []
      deprecated: false
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Shouts[Shout]'
      tags:
        - Shouts
  /api/shouts/top:
    get:
      consumes: []
      deprecated: false
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Shouts[Shout]'
      tags:
        - Shouts
  '/api/shouts/{Handle}':
    get:
      consumes: []
      deprecated: false
      parameters:
        - in: path
          name: Handle
          required: true
          type: string
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Shouts[Shout]'
      tags:
        - Shouts
definitions:
  Shout:
    properties:
      Handle:
        type: string
      Keywords:
        type: string
      MP3Url:
        type: string
      Score:
        format: int32
        type: integer
      ShoutDateTime:
        type: string
      Sid:
        type: string
      State:
        type: string
      TimeAgo:
        type: string
    type: object
  'Shouts[Shout]':
    properties:
      ct:
        type: string
      recs:
        format: int32
        type: integer
      results:
        items:
          $ref: '#/definitions/Shout'
        type: array
    type: object
